# This file will be added once by Ansible/Vagrant, but then will not be replaced
# if you provision the machine again, to allow you to customize your
# environment.

source ~/.bashrc

export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

# Needed for running PhantomJS on Ubuntu 16.04
export QT_QPA_PLATFORM=offscreen
export GEM_HOME=~/.gem
export PATH=$PATH:~/.gem/ruby/2.3.0/bin



